server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 50M;

    location = / {
        return 302 /efor-sarayi/;
    }

    location = /efor-sarayi {
        return 302 /efor-sarayi/;
    }

    location /efor-sarayi/ {
        rewrite ^/efor-sarayi/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }
}
